// src/examples/obstacle-course/obstacle-course.svelte
<script>
  const avengers = [
    'Iron Man',
    'Black Widow',
    'Thor',
    'Hulk',
    'Captain America',
    'Hawkeye',
  ];
  const toppingChoices = ['Lettuce', 'Tomato', 'Onion', 'Sardines'];
  const beatles = ['John', 'Paul', 'George', 'Ringo'];

  let text = '';
  let favoriteAvenger = 'Black Widow';
  let toppings = [];
  let favoriteBeatle = 'Paul';
  let color = '#FF0000';
  let date = '2021-12-17';
  let rating = '4';
  let file = '';
</script>

<svelte:head>
  <title>Input Obstacle Course</title>
</svelte:head>

<main class="grid grid-cols-2 gap-4">
  <div class="p-2 border-2 border-purple-300">
    <label for="deep-thought">Deep Thought</label>
    <input
      placeholder="Some text…"
      id="deep-thought"
      bind:value={text}
      data-test="text-input"
    />
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="text-result">{text}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <label for="avenger">Favorite Avenger</label>
    <select bind:value={favoriteAvenger} id="avenger" data-test="select-input">
      {#each avengers as avenger}
        <option>{avenger}</option>
      {/each}
    </select>
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="select-result">{favoriteAvenger || 'No one'}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <h3>Toppings</h3>
    {#each toppingChoices as topping}
      <label class="mb-0" for={topping.toLocaleLowerCase()}>
        <input
          type="checkbox"
          id={topping.toLocaleLowerCase()}
          bind:group={toppings}
          name="toppings"
          value={topping}
          data-test="checkbox-{topping.toLocaleLowerCase()}"
        />
        {topping}
      </label>
    {/each}
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="checkbox-result">{toppings.join(', ') || '(None)'}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <h3>Favorite Beatle</h3>
    {#each beatles as beatle}
      <label class="list" for={beatle.toLowerCase()}>
        <input
          type="radio"
          name="beatles"
          id={beatle.toLowerCase()}
          value={beatle}
          bind:group={favoriteBeatle}
          data-test="radio-{beatle.toLowerCase()}"
        />
        {beatle}
      </label>
    {/each}
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="radio-result">{favoriteBeatle}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <label for="color">Favorite Color</label><input
      type="color"
      class="h-10 w-20"
      id="color"
      bind:value={color}
      data-test="color-input"
    />
  </div>
  <div
    class="p-2 border-2 border-purple-300 flex items-center justify-around"
    style="color: {color}"
    data-test="color-container"
  >
    <p data-test="color-result">{color}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <label for="date">Date</label><input
      type="date"
      name="date"
      id="date"
      bind:value={date}
      data-test="date-input"
    />
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="date-result">{date}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <label for="rating">Rating</label><input
      type="range"
      name="rating"
      id="rating"
      min="0"
      max="10"
      bind:value={rating}
      data-test="range-input"
    />
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="range-result">{rating}</p>
  </div>
  <div class="p-2 border-2 border-purple-300">
    <label for="resume">Résumé</label><input
      type="file"
      name="resume"
      id="resume"
      bind:value={file}
      data-test="file-input"
    />
  </div>
  <div class="p-2 border-2 border-purple-300 flex items-center justify-around">
    <p data-test="file-result">{file || ''}</p>
  </div>
</main>

// src/examples/obstacle-course/index.tsx
import { useReducer, useState } from 'react';

const avengers = [
  'Iron Man',
  'Black Widow',
  'Thor',
  'Hulk',
  'Captain America',
  'Hawkeye',
] as const;

const toppingsState = {
  Onion: false,
  Sardines: false,
  Tomato: false,
  Lettuce: false,
} as const;

const toppings = Object.keys(toppingsState);

const beatles = ['John', 'Paul', 'George', 'Ringo'];

type Topping = keyof typeof toppingsState;
type Beatle = (typeof beatles)[number];

const toppingsReducer = (
  toppings: Record<Topping, boolean> = {
    Onion: false,
    Sardines: false,
    Tomato: false,
    Lettuce: false,
  },
  action: { topping: Topping; checked: boolean },
) => {
  return { ...toppings, [action.topping]: action.checked };
};

const isTopping = (s: string): s is Topping => {
  return toppings.includes(s);
};

const ObstacleCourse = () => {
  const [text, setText] = useState<string>('');
  const [favoriteAvenger, setFavoriteAvenger] = useState<string>('Black Widow');
  const [toppings, dispatch] = useReducer(toppingsReducer, toppingsState);
  const [favoriteBeatle, setFavoriteBeatle] = useState<Beatle>('Paul');
  const [color, setColor] = useState<string>('#FF0000');
  const [date, setDate] = useState<string>('2021-12-17');
  const [rating, setRating] = useState('4');
  const [file, setFile] = useState<string>('');

  return (
    <div className="grid grid-cols-2 gap-4">
      <div className="flex items-center gap-2 border-2 border-purple-300 p-2">
        <label htmlFor="deep-thought">Deep Thought</label>
        <input
          placeholder="Some text…"
          id="deep-thought"
          value={text}
          onChange={(e) => setText(e.target.value)}
          data-testid="text-input"
        />
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="text-result">{text}</p>
      </div>
      <div className="border-2 border-purple-300 p-2">
        <label htmlFor="avenger">Favorite Avenger</label>
        <select
          value={favoriteAvenger}
          id="avenger"
          data-testid="select-input"
          onChange={(e) => setFavoriteAvenger(e.target.value)}
        >
          {avengers.map((avenger) => (
            <option key={avenger}>{avenger}</option>
          ))}
        </select>
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="select-result">{favoriteAvenger || 'No one'}</p>
      </div>
      <div className="border-2 border-purple-300 p-2">
        <h3>Toppings</h3>
        {Object.keys(toppingsState).map((topping) => (
          <div className="flex items-center gap-2" key={topping}>
            <input
              type="checkbox"
              id={topping.toLocaleLowerCase()}
              name="toppings"
              value={topping}
              onChange={(e) => {
                if (!isTopping(e.target.value)) return;
                dispatch({
                  topping: e.target.value,
                  checked: e.target.checked,
                });
              }}
              data-testid="checkbox-{topping.toLocaleLowerCase()}"
            />
            <label className="list" htmlFor={topping.toLocaleLowerCase()}>
              {topping}
            </label>
          </div>
        ))}
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="checkbox-result">
          {Object.keys(toppings).join(', ') || '(None)'}
        </p>
      </div>
      <div className="border-2 border-purple-300 p-2">
        <h3>Favorite Beatle</h3>
        {beatles.map((beatle) => (
          <div className="flex items-center gap-2" key={beatle}>
            <input
              type="radio"
              name="beatles"
              id={beatle.toLowerCase()}
              value={beatle}
              onChange={(e) => setFavoriteBeatle(e.target.value)}
              data-testid="radio-{beatle.toLowerCase()}"
            />
            <label className="list" htmlFor={beatle.toLowerCase()}>
              {beatle}
            </label>
          </div>
        ))}
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="radio-result">{favoriteBeatle}</p>
      </div>
      <div className="flex items-center gap-2 border-2 border-purple-300 p-2">
        <label htmlFor="color">Favorite Color</label>
        <input
          type="color"
          className="h-10 w-20"
          id="color"
          value={color}
          onChange={(e) => setColor(e.target.value)}
          data-testid="color-input"
        />
      </div>
      <div
        className="flex items-center justify-around gap-2 border-2 border-purple-300 p-2"
        style={{ color }}
        data-testid="color-container"
      >
        <p data-testid="color-result">{color}</p>
      </div>
      <div className="flex items-center gap-2 border-2 border-purple-300 p-2">
        <label htmlFor="date">Date</label>
        <input
          type="date"
          name="date"
          id="date"
          value={date}
          onChange={(e) => setDate(e.target.value)}
          data-testid="date-input"
        />
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="date-result">{date}</p>
      </div>
      <div className="border-2 border-purple-300 p-2">
        <label htmlFor="rating">Rating</label>
        <input
          type="range"
          name="rating"
          id="rating"
          min="0"
          max="10"
          value={rating}
          onChange={(e) => setRating(e.target.value)}
          data-testid="range-input"
        />
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="range-result">{rating}</p>
      </div>
      <div className="flex items-center gap-2 border-2 border-purple-300 p-2">
        <label htmlFor="resume">Résumé</label>
        {/*<input />*/}
        <input
          type="file"
          name="resume"
          id="resume"
          value={file}
          onChange={(e) => setFile(e.target.value)}
          data-testid="file-input"
        />
      </div>
      <div className="flex items-center justify-around border-2 border-purple-300 p-2">
        <p data-testid="file-result">{file || ''}</p>
      </div>
    </div>
  );
};

export default ObstacleCourse;
